#!/bin/sh
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# <LicenseText>
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#


#export GEOFRAMEWORK=
export CITCOMSHOME=$GEOFRAMEWORK/packages/CitcomS
export PATH=$CITCOMSHOME/visual:$PATH

if [ x$DXMACROS = "x" ]; then
	export DXMACROS=""
fi

export DXMACROS=$CITCOMSHOME/visual/OpenDXMacro:$DXMACROS


# version
# $Id: citcoms_profile,v 1.1 2004/06/02 21:49:37 tan2 Exp $

# End of file
